require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SitemarxModelsController do

  # This should return the minimal set of attributes required to create a valid
  # SitemarxModel. As you add validations to SitemarxModel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "url" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SitemarxModelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sitemarx_models as @sitemarx_models" do
      sitemarx_model = SitemarxModel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sitemarx_models).should eq([sitemarx_model])
    end
  end

  describe "GET show" do
    it "assigns the requested sitemarx_model as @sitemarx_model" do
      sitemarx_model = SitemarxModel.create! valid_attributes
      get :show, {:id => sitemarx_model.to_param}, valid_session
      assigns(:sitemarx_model).should eq(sitemarx_model)
    end
  end

  describe "GET new" do
    it "assigns a new sitemarx_model as @sitemarx_model" do
      get :new, {}, valid_session
      assigns(:sitemarx_model).should be_a_new(SitemarxModel)
    end
  end

  describe "GET edit" do
    it "assigns the requested sitemarx_model as @sitemarx_model" do
      sitemarx_model = SitemarxModel.create! valid_attributes
      get :edit, {:id => sitemarx_model.to_param}, valid_session
      assigns(:sitemarx_model).should eq(sitemarx_model)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SitemarxModel" do
        expect {
          post :create, {:sitemarx_model => valid_attributes}, valid_session
        }.to change(SitemarxModel, :count).by(1)
      end

      it "assigns a newly created sitemarx_model as @sitemarx_model" do
        post :create, {:sitemarx_model => valid_attributes}, valid_session
        assigns(:sitemarx_model).should be_a(SitemarxModel)
        assigns(:sitemarx_model).should be_persisted
      end

      it "redirects to the created sitemarx_model" do
        post :create, {:sitemarx_model => valid_attributes}, valid_session
        response.should redirect_to(SitemarxModel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sitemarx_model as @sitemarx_model" do
        # Trigger the behavior that occurs when invalid params are submitted
        SitemarxModel.any_instance.stub(:save).and_return(false)
        post :create, {:sitemarx_model => { "url" => "invalid value" }}, valid_session
        assigns(:sitemarx_model).should be_a_new(SitemarxModel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SitemarxModel.any_instance.stub(:save).and_return(false)
        post :create, {:sitemarx_model => { "url" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sitemarx_model" do
        sitemarx_model = SitemarxModel.create! valid_attributes
        # Assuming there are no other sitemarx_models in the database, this
        # specifies that the SitemarxModel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SitemarxModel.any_instance.should_receive(:update).with({ "url" => "MyString" })
        put :update, {:id => sitemarx_model.to_param, :sitemarx_model => { "url" => "MyString" }}, valid_session
      end

      it "assigns the requested sitemarx_model as @sitemarx_model" do
        sitemarx_model = SitemarxModel.create! valid_attributes
        put :update, {:id => sitemarx_model.to_param, :sitemarx_model => valid_attributes}, valid_session
        assigns(:sitemarx_model).should eq(sitemarx_model)
      end

      it "redirects to the sitemarx_model" do
        sitemarx_model = SitemarxModel.create! valid_attributes
        put :update, {:id => sitemarx_model.to_param, :sitemarx_model => valid_attributes}, valid_session
        response.should redirect_to(sitemarx_model)
      end
    end

    describe "with invalid params" do
      it "assigns the sitemarx_model as @sitemarx_model" do
        sitemarx_model = SitemarxModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SitemarxModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => sitemarx_model.to_param, :sitemarx_model => { "url" => "invalid value" }}, valid_session
        assigns(:sitemarx_model).should eq(sitemarx_model)
      end

      it "re-renders the 'edit' template" do
        sitemarx_model = SitemarxModel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SitemarxModel.any_instance.stub(:save).and_return(false)
        put :update, {:id => sitemarx_model.to_param, :sitemarx_model => { "url" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sitemarx_model" do
      sitemarx_model = SitemarxModel.create! valid_attributes
      expect {
        delete :destroy, {:id => sitemarx_model.to_param}, valid_session
      }.to change(SitemarxModel, :count).by(-1)
    end

    it "redirects to the sitemarx_models list" do
      sitemarx_model = SitemarxModel.create! valid_attributes
      delete :destroy, {:id => sitemarx_model.to_param}, valid_session
      response.should redirect_to(sitemarx_models_url)
    end
  end

end
